import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen max-w-[420px] mx-auto px-7 py-6 flex flex-col bg-[#F9F5FF]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
